In [1]:
import numpy as np

In [5]:
L = [1,4,5,5,6,8,6,4]

In [6]:
np.array(L)

array([1, 4, 5, 5, 6, 8, 6, 4])

In [8]:
arr = np.array(L, float)
arr

array([1., 4., 5., 5., 6., 8., 6., 4.])

In [9]:
arr[5]

8.0

In [10]:
arr[1:4]

array([4., 5., 5.])

In [11]:
arr[-4]

6.0

In [12]:
arr[:3]

array([1., 4., 5.])

In [13]:
arr[-3:]

array([8., 6., 4.])

In [14]:
L = [1,4,7,'8']

In [16]:
arr = np.array(L) # numpy array는 모두 동일한 데이터 타입의 원소를 갖는다.
arr

array(['1', '4', '7', '8'], dtype='<U11')

In [17]:
arr.ndim # 1차원 : vector, 2차원 : matrix, 3차원 : tensor

1

In [18]:
arr.shape # 원소 하나의 1차원 vector

(4,)

In [ ]:
# matrix 2차원 행과 열을 가짐

In [19]:
L = [[1,2,3,4], [4,8,3,5], [6,7,8,5]]

In [21]:
mat = np.array(L)
mat

array([[1, 2, 3, 4],
       [4, 8, 3, 5],
       [6, 7, 8, 5]])

In [22]:
mat.shape

(3, 4)

In [23]:
mat.ndim

2

In [24]:
# tensor 3차원

In [25]:
T = [[[1,2,3,4], [4,8,3,5], [6,7,8,5]],
[[1,2,3,4], [4,8,3,5], [6,7,8,5]],
[[1,2,3,4], [4,8,3,5], [6,7,8,5]]]

In [27]:
tensor = np.array(T)
tensor

array([[[1, 2, 3, 4],
        [4, 8, 3, 5],
        [6, 7, 8, 5]],

       [[1, 2, 3, 4],
        [4, 8, 3, 5],
        [6, 7, 8, 5]],

       [[1, 2, 3, 4],
        [4, 8, 3, 5],
        [6, 7, 8, 5]]])

In [29]:
tensor.shape # 앞에서부터 읽으면 3개의 매트릭스가 있는데 각 하나가 3행 4열이다.

(3, 3, 4)

### reshape

In [32]:
L = [[1,3,5,6], [7,8,5,4]]
mat = np.array(L)
mat

array([[1, 3, 5, 6],
       [7, 8, 5, 4]])

In [34]:
mat.shape # 2행 4열

(2, 4)

In [35]:
mat.ndim

2

In [36]:
mat.size

8

In [37]:
mat

array([[1, 3, 5, 6],
       [7, 8, 5, 4]])

In [40]:
mat.reshape(8) #1차원으로 바뀜

array([1, 3, 5, 6, 7, 8, 5, 4])

In [39]:
mat.reshape(4,2)

array([[1, 3],
       [5, 6],
       [7, 8],
       [5, 4]])

In [41]:
mat.reshape(2,2,2)

array([[[1, 3],
        [5, 6]],

       [[7, 8],
        [5, 4]]])

In [42]:
mat.reshape(3,4) # reshape을 하는데 size가 안 맞아서 에러

ValueError: cannot reshape array of size 8 into shape (3,4)

In [43]:
L = [[1,2,3,4], [5,5,6,5], [8,6,4,6]]

In [44]:
mat = np.array(L)
mat

array([[1, 2, 3, 4],
       [5, 5, 6, 5],
       [8, 6, 4, 6]])

In [45]:
mat.shape

(3, 4)

In [46]:
mat.size

12

In [47]:
mat.ndim

2

In [48]:
mat.reshape(2,6)

array([[1, 2, 3, 4, 5, 5],
       [6, 5, 8, 6, 4, 6]])

In [49]:
mat.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 5],
       [6, 5, 8],
       [6, 4, 6]])

In [50]:
mat.reshape(12)

array([1, 2, 3, 4, 5, 5, 6, 5, 8, 6, 4, 6])

In [51]:
mat.reshape(-1, 6) # 행은 모르겠고 열만 6개로 맞춰!!!

array([[1, 2, 3, 4, 5, 5],
       [6, 5, 8, 6, 4, 6]])

### indexing, slicing

In [52]:
mat

array([[1, 2, 3, 4],
       [5, 5, 6, 5],
       [8, 6, 4, 6]])

In [55]:
mat[0:2, 1:3] # mat[행, 열]

array([[2, 3],
       [5, 6]])

In [56]:
mat[1:, 2:]

array([[6, 5],
       [4, 6]])

In [57]:
mat[:2, 1::2]

array([[2, 4],
       [5, 5]])

In [60]:
mat[1, 1:3]

array([5, 6])

In [61]:
# mat[행, 열]
# 행 - 가로, row
# 열 - 세로, columns

In [63]:
mat[-1, -1] =100
mat

array([[  1,   2,   3,   4],
       [  5,   5,   6,   5],
       [  8,   6,   4, 100]])

In [64]:
L = [1,3,4,5,6]

In [65]:
sum(L)

19

In [66]:
min(L)

1

In [67]:
max(L)

6

In [68]:
len(L)

5

In [69]:
sum(L)/len(L)

3.8

In [74]:
mat.sum(axis=0)

array([ 14,  13,  13, 109])

In [75]:
mat.sum(axis=1)

array([ 10,  21, 118])

In [76]:
mat.max(axis=0)

array([  8,   6,   6, 100])

In [77]:
mat.max(axis=1)

array([  4,   6, 100])

In [80]:
mat.std(axis=1) # 표준편차

array([ 1.11803399,  0.4330127 , 40.72775466])

In [81]:
mat.var(axis=0) # 분산

array([8.22222222e+00, 2.88888889e+00, 1.55555556e+00, 2.02688889e+03])

In [82]:
# np.sqrt: 제곱근

np.sqrt(mat)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.23606798,  2.44948974,  2.23606798],
       [ 2.82842712,  2.44948974,  2.        , 10.        ]])

In [83]:
# python에서 연속값을 생성하는 함수

In [85]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [86]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [87]:
# 연속값을 생성하는 arange

In [88]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [91]:
range(1, 10, 0.5) # 파이썬에서는 range가 간격이 정수만 가능

TypeError: 'float' object cannot be interpreted as an integer

In [93]:
np.arange(1, 10, 0.1) # numpy에서는 range 간격이 소수도 가능

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

### numpy의 연산은 element wise operation - 동일한 인덱스 요소간의 연산

In [94]:
mat1 = np.array([[1,2,3,4], [4,5,6,7]])
mat2 = np.array([[7,8,5,4], [4,3,2,1]])

In [95]:
mat1

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [96]:
mat2

array([[7, 8, 5, 4],
       [4, 3, 2, 1]])

In [97]:
mat1+mat2

array([[ 8, 10,  8,  8],
       [ 8,  8,  8,  8]])

In [98]:
vec1 = np.array([5,6,7,8])
vec1

array([5, 6, 7, 8])

In [99]:
# broadcating operation : shape이 다른 array간에 shape을 확장시켜서 연산하도록
mat1+vec1

array([[ 6,  8, 10, 12],
       [ 9, 11, 13, 15]])

In [100]:
mat1 + 2

array([[3, 4, 5, 6],
       [6, 7, 8, 9]])

In [101]:
mat1 - mat2

array([[-6, -6, -2,  0],
       [ 0,  2,  4,  6]])

In [102]:
mat1 / mat2

array([[0.14285714, 0.25      , 0.6       , 1.        ],
       [1.        , 1.66666667, 3.        , 7.        ]])