In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

In [5]:
np.any(a>5)

True

In [6]:
np.all(a<0)

False

In [7]:
test_a = np.array([1,3,0], float)
test_a

array([1., 3., 0.])

In [8]:
test_b = np.array([5,2,1], float)
test_b

array([5., 2., 1.])

In [9]:
test_a + test_b

array([6., 5., 1.])

In [10]:
test_a * test_b

array([5., 6., 0.])

In [12]:
test_a > test_b

array([False,  True, False])

In [13]:
test_a == test_b

array([False, False, False])

In [14]:
np.any(test_a > test_b)

True

In [15]:
np.all(test_a > test_b)

False

### boolean indexing

In [16]:
test_array = np.array([1,4,0,2,3,8,9,7])
test_array

array([1, 4, 0, 2, 3, 8, 9, 7])

In [17]:
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [19]:
test_array[test_array>3] # 3보다 큰지 비교 연산 후 True인 값들만 출력

array([4, 8, 9, 7])

In [20]:
names = np.array(['bon', 'kim', 'jim', 'park'])
names

array(['bon', 'kim', 'jim', 'park'], dtype='<U4')

In [21]:
# boolean indexing을 통해서 'kim을 출력하시오'

In [23]:
names == 'kim'

array([False,  True, False, False])

In [22]:
names[names=='kim'] 

array(['kim'], dtype='<U4')

In [24]:
names[[False,  True, False, False]] 

array(['kim'], dtype='<U4')

In [25]:
# names에서 'kim'이 아닌 사람을 boolean indexing으로 출력

In [26]:
names != 'kim'

array([ True, False,  True,  True])

In [27]:
names[names != 'kim']

array(['bon', 'jim', 'park'], dtype='<U4')

In [30]:
randarr = np.random.randn(7,4) #rand 메소드는 0부터1까지 임의의 난수 생성, randn는 평균 0 표준편차1인 정규분포상의 난수 생성
randarr

array([[ 0.43606102, -0.3939731 , -0.06793228, -1.08566083],
       [ 1.65713212, -1.21021037, -0.19948869,  0.36919944],
       [ 0.17451514,  0.46707109, -0.91323266,  0.6492238 ],
       [ 1.00043018,  2.18695565,  0.70018223, -0.35301131],
       [ 0.08167246, -1.33723834,  0.44529763, -0.08817536],
       [ 1.27801752, -0.73403729, -4.01284837, -0.37456305],
       [-0.23007851,  1.86392067,  0.09347434, -0.18652196]])

In [31]:
# boolean index를 통해서 0보다 큰 값만 출력

In [32]:
randarr >0

array([[ True, False, False, False],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [False,  True,  True, False]])

In [34]:
randarr[randarr>0]

array([0.43606102, 1.65713212, 0.36919944, 0.17451514, 0.46707109,
       0.6492238 , 1.00043018, 2.18695565, 0.70018223, 0.08167246,
       0.44529763, 1.27801752, 1.86392067, 0.09347434])

In [35]:
# 1~100까지 정수에서 20보다 크고 70보다 작은 3의 배수 출력

In [48]:
mat1 = np.arange(1, 101)
mat1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [49]:
mat1 > 20

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [50]:
mat1 < 70

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [51]:
mat1%3 == 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False])

In [52]:
(mat1 > 20) & (mat1 < 70) & (mat1%3 == 0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [53]:
mat1[(mat1 > 20) & (mat1 < 70) & (mat1%3 == 0)]

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69])

In [54]:
# fancy index

In [55]:
arr = np.array([2,3,4,5,4,7,6,8,6])
arr

array([2, 3, 4, 5, 4, 7, 6, 8, 6])

In [56]:
arr[5]

7

In [57]:
arr[5:8]

array([7, 6, 8])

In [58]:
arr[:5]

array([2, 3, 4, 5, 4])

In [62]:
arr[[1,5,6]] # 실제 구현해보니 생각보다 허무 이름만 거창 ㅋㅋㅋ

array([3, 7, 6])