In [1]:
import numpy as np

In [2]:
L = [1,4,5,5,6,8,6,4]

In [3]:
np.array(L)

array([1, 4, 5, 5, 6, 8, 6, 4])

In [4]:
arr = np.array(L, float)
arr

array([1., 4., 5., 5., 6., 8., 6., 4.])

In [6]:
arr[1:4]

array([4., 5., 5.])

In [7]:
L = [1,4,7,'8']

In [8]:
arr = np.array(L)
arr

array(['1', '4', '7', '8'], dtype='<U11')

In [11]:
arr.ndim

1

In [14]:
arr.shape

(4,)

In [15]:
L = [[1,2,3,4], [4,8,3,5], [6,7,8,5]]

In [16]:
mat = np.array(L)
mat

array([[1, 2, 3, 4],
       [4, 8, 3, 5],
       [6, 7, 8, 5]])

In [17]:
mat.shape

(3, 4)

In [18]:
mat.ndim

2

In [19]:
T = [[[1,2,3,4], [4,9,3,5], [6,7,9,5]],
    [[1,2,3,4], [4,8,3,5], [6,7,8,5]],
    [[1,2,3,4], [4,8,3,5], [6,7,8,5]]]

In [20]:
tensor = np.array(T)
tensor

array([[[1, 2, 3, 4],
        [4, 9, 3, 5],
        [6, 7, 9, 5]],

       [[1, 2, 3, 4],
        [4, 8, 3, 5],
        [6, 7, 8, 5]],

       [[1, 2, 3, 4],
        [4, 8, 3, 5],
        [6, 7, 8, 5]]])

In [21]:
tensor.shape

(3, 3, 4)

In [22]:
tensor.ndim

3

In [23]:
L = [[1,3,5,6], [4,2,5,6]]
mat = np.array(L)
mat

array([[1, 3, 5, 6],
       [4, 2, 5, 6]])

In [27]:
mat.reshape(8)

array([1, 3, 5, 6, 4, 2, 5, 6])

In [28]:
mat.reshape(4,2)

array([[1, 3],
       [5, 6],
       [4, 2],
       [5, 6]])

In [29]:
mat.reshape(2,2,2)

array([[[1, 3],
        [5, 6]],

       [[4, 2],
        [5, 6]]])

In [32]:
mat.reshape(-1,4)

array([[1, 3, 5, 6],
       [4, 2, 5, 6]])

In [38]:
L = [[1,2,3,4],
    [5,5,6,5],
    [8,6,4,6]]

In [39]:
mat = np.array(L)

In [40]:
mat

array([[1, 2, 3, 4],
       [5, 5, 6, 5],
       [8, 6, 4, 6]])

In [41]:
mat[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [44]:
mat[:2, 1::2]

array([[2, 4],
       [5, 5]])

In [45]:
mat[1, 1:3]

array([5, 6])

In [46]:
mat[-1, -1] = 100

In [47]:
mat

array([[  1,   2,   3,   4],
       [  5,   5,   6,   5],
       [  8,   6,   4, 100]])

In [49]:
mat.sum(axis=0)

array([ 14,  13,  13, 109])

In [50]:
mat.sum(axis=1)

array([ 10,  21, 118])

In [51]:
mat.std(axis=1)

array([ 1.11803399,  0.4330127 , 40.72775466])

In [55]:
mat.var(axis=0)

array([8.22222222e+00, 2.88888889e+00, 1.55555556e+00, 2.02688889e+03])

In [53]:
np.sqrt(mat)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.23606798,  2.44948974,  2.23606798],
       [ 2.82842712,  2.44948974,  2.        , 10.        ]])

In [56]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [59]:
mat1 = np.array([[1,2,3,4], [5,3,6,7]])
mat2 = np.array([[2,3,6,3], [3,5,6,7]])

In [60]:
mat1+mat2

array([[ 3,  5,  9,  7],
       [ 8,  8, 12, 14]])

In [61]:
vec1 = np.array([1,2,3,4])

In [62]:
mat1+vec1

array([[ 2,  4,  6,  8],
       [ 6,  5,  9, 11]])

In [63]:
test_array = np.array([1,4,0,2,3,8,9,7])
test_array

array([1, 4, 0, 2, 3, 8, 9, 7])

In [64]:
test_array>3

array([False,  True, False, False, False,  True,  True,  True])

In [65]:
test_array[test_array>3]

array([4, 8, 9, 7])

In [66]:
names = np.array(['bon', 'kim', 'jim', 'park'])
names

array(['bon', 'kim', 'jim', 'park'], dtype='<U4')

In [67]:
names =='kim'

array([False,  True, False, False])

In [68]:
names[names=='kim']

array(['kim'], dtype='<U4')

In [69]:
names[names!='kim']

array(['bon', 'jim', 'park'], dtype='<U4')

In [71]:
randarr = np.random.randn(7,4)
randarr

array([[-0.78130082, -0.83485139, -0.05873024,  1.95327122],
       [-0.13145434,  0.54137786, -1.32637285,  0.60368651],
       [-0.02917202,  0.4042111 , -0.75105468,  2.11286613],
       [ 0.29791753, -1.53053058,  1.16277239, -1.23271379],
       [ 1.38163782,  0.44076563, -1.10328208,  0.51829057],
       [-0.22689974, -0.20783155, -0.16286442,  0.18782039],
       [-0.10974845, -0.4630004 ,  0.12260837, -0.46583626]])

In [72]:
randarr>0

array([[False, False, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [ True, False,  True, False],
       [ True,  True, False,  True],
       [False, False, False,  True],
       [False, False,  True, False]])

In [73]:
randarr[randarr>0]

array([1.95327122, 0.54137786, 0.60368651, 0.4042111 , 2.11286613,
       0.29791753, 1.16277239, 1.38163782, 0.44076563, 0.51829057,
       0.18782039, 0.12260837])

In [74]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [75]:
a[(a>20) & (a<70) & (a%3==0)]

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69])

In [78]:
import pandas as pd
import numpy as np

In [85]:
L = [1,2,3,5]
pd.Series(L, index=['a','b','c','d'])

a    1
b    2
c    3
d    5
dtype: int64

In [212]:
S = {'a':1, 'b':2, 'c':3, 'd':4}
d = pd.Series(S, index=['a','b','c','d', 'e', 'f'])
d

a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
f    NaN
dtype: float64

In [87]:
d['c']

3.0

In [89]:
d['f'] = 100

In [90]:
d

a      1.0
b      2.0
c      3.0
d      4.0
e      NaN
f    100.0
dtype: float64

In [91]:
L.index

<function list.index(value, start=0, stop=2147483647, /)>

In [92]:
d.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [94]:
d.values

array([  1.,   2.,   3.,   4.,  nan, 100.])

In [214]:
raw_data = {
    'first_name': ['jason', 'molly', 'tina', 'jake'],
    'last_name': ['miller', 'jacob', 'ali', 'milner'],
    'age': [42,52,36,24],
    'city': ['san francisco', 'baltimore', 'maimi', 'boston']
}
raw_data

{'first_name': ['jason', 'molly', 'tina', 'jake'],
 'last_name': ['miller', 'jacob', 'ali', 'milner'],
 'age': [42, 52, 36, 24],
 'city': ['san francisco', 'baltimore', 'maimi', 'boston']}

In [215]:
df = pd.DataFrame(raw_data)
df

first_name last_name  age           city
0      jason    miller   42  san francisco
1      molly     jacob   52      baltimore
2       tina       ali   36          maimi
3       jake    milner   24         boston

In [217]:
pd.DataFrame(raw_data, columns=['first_name', 'last_name', 'age', 'city'])

first_name last_name  age           city
0      jason    miller   42  san francisco
1      molly     jacob   52      baltimore
2       tina       ali   36          maimi
3       jake    milner   24         boston

In [102]:
pd.DataFrame(raw_data, columns=['last_name', 'first_name'])

last_name first_name
0    miller      jason
1     jacob      molly
2       ali       tina
3    milner       jake

In [104]:
df[['age', 'city']]

age           city
0   42  san francisco
1   52      baltimore
2   36          maimi
3   24         boston

In [106]:
df.index = ['a', 'b', 'c', 'd']
df

first_name last_name  age           city
a      jason    miller   42  san francisco
b      molly     jacob   52      baltimore
c       tina       ali   36          maimi
d       jake    milner   24         boston

In [111]:
df.loc[['b', 'c', 'd'], ['last_name', 'age']]

last_name  age
b     jacob   52
c       ali   36
d    milner   24

In [112]:
df.iloc[[1,2,3], [1,2]]

last_name  age
b     jacob   52
c       ali   36
d    milner   24

In [114]:
df.iloc[1:4, 1:3]

last_name  age
b     jacob   52
c       ali   36
d    milner   24

In [116]:
df.iloc[:,:3]

first_name last_name  age
a      jason    miller   42
b      molly     jacob   52
c       tina       ali   36
d       jake    milner   24

In [121]:
df.loc[:, :'age']

first_name last_name  age
a      jason    miller   42
b      molly     jacob   52
c       tina       ali   36
d       jake    milner   24

In [122]:
df.iloc[[1,2], 1:3]

last_name  age
b     jacob   52
c       ali   36

In [124]:
df.loc[['b','c','d'], 'first_name':'age']

first_name last_name  age
b      molly     jacob   52
c       tina       ali   36
d       jake    milner   24

In [127]:
df['city']=='maimi'

a    False
b    False
c     True
d    False
Name: city, dtype: bool

In [128]:
df[df['city']=='maimi']

first_name last_name  age   city
c       tina       ali   36  maimi

In [129]:
df[df['city']=='maimi']['age']

c    36
Name: age, dtype: int64

In [130]:
df.T

a          b      c       d
first_name          jason      molly   tina    jake
last_name          miller      jacob    ali  milner
age                    42         52     36      24
city        san francisco  baltimore  maimi  boston

In [131]:
df.drop('a')

first_name last_name  age       city
b      molly     jacob   52  baltimore
c       tina       ali   36      maimi
d       jake    milner   24     boston

In [133]:
df.drop('city', axis=1)

first_name last_name  age
a      jason    miller   42
b      molly     jacob   52
c       tina       ali   36
d       jake    milner   24

In [134]:
df['age']+1

a    43
b    53
c    37
d    25
Name: age, dtype: int64

In [135]:
df['age'] = df['age'].apply(lambda x: x+1)

In [136]:
df

first_name last_name  age           city
a      jason    miller   43  san francisco
b      molly     jacob   53      baltimore
c       tina       ali   37          maimi
d       jake    milner   25         boston

In [137]:
wages = pd.read_csv('./wages.csv')
wages

earn  height     sex   race  ed  age
0     79571.299011   73.89    male  white  16   49
1     96396.988643   66.23  female  white  16   62
2     48710.666947   63.77  female  white  16   33
3     80478.096153   63.22  female  other  16   95
4     82089.345498   63.08  female  white  17   43
...            ...     ...     ...    ...  ..  ...
1374  30173.380363   71.68    male  white  12   33
1375  24853.519514   61.31  female  white  18   86
1376  13710.671312   63.64  female  white  12   37
1377  95426.014410   71.65    male  white  12   54
1378   9575.461857   68.22    male  white  12   31

[1379 rows x 6 columns]

In [139]:
wages['height'] = wages['height'].apply(lambda x: int(x))
wages.head()

earn  height     sex   race  ed  age
0  79571.299011      73    male  white  16   49
1  96396.988643      66  female  white  16   62
2  48710.666947      63  female  white  16   33
3  80478.096153      63  female  other  16   95
4  82089.345498      63  female  white  17   43

In [141]:
wages.groupby('sex')['earn'].mean()

sex
female    24245.647877
male      45993.126922
Name: earn, dtype: float64

In [144]:
wages['race'].unique()

array(['white', 'other', 'hispanic', 'black'], dtype=object)

In [148]:
race_dict = {'white':0, 'other':1, 'hispanice':2, 'black':3}
wages['race'] = wages['race'].map(race_dict)
wages

earn  height     sex  race  ed  age
0     79571.299011      73    male   0.0  16   49
1     96396.988643      66  female   0.0  16   62
2     48710.666947      63  female   0.0  16   33
3     80478.096153      63  female   1.0  16   95
4     82089.345498      63  female   0.0  17   43
...            ...     ...     ...   ...  ..  ...
1374  30173.380363      71    male   0.0  12   33
1375  24853.519514      61  female   0.0  18   86
1376  13710.671312      63  female   0.0  12   37
1377  95426.014410      71    male   0.0  12   54
1378   9575.461857      68    male   0.0  12   31

[1379 rows x 6 columns]

In [152]:
data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings', 'Giant', 'Kings', \
                'Kings', 'Riders', 'Royals','Royals', 'Riders'],
       'Rank':[1,2,2,3,3,4,1,1,2,4,1,2],
       'Year':[2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
       'Points':[876,788,863,673,741,812,756,788,694,721,804,923]}
df = pd.DataFrame(data)
df

Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     788
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Giant     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     721
10  Royals     1  2015     804
11  Riders     2  2017     923

In [154]:
grouped = df.groupby('Team')

In [157]:
grouped.get_group('Royals')

Team  Rank  Year  Points
9   Royals     4  2014     721
10  Royals     1  2015     804

In [158]:
grouped.get_group('Kings')

Team  Rank  Year  Points
4  Kings     3  2014     741
6  Kings     1  2016     756
7  Kings     1  2017     788

In [159]:
grouped.min()

Rank  Year  Points
Team                      
Devils     2  2014     673
Giant      4  2015     812
Kings      1  2014     741
Riders     1  2014     694
Royals     1  2014     721

In [160]:
grouped['Points'].mean()

Team
Devils    768.000000
Giant     812.000000
Kings     761.666667
Riders    820.250000
Royals    762.500000
Name: Points, dtype: float64

In [162]:
import numpy as np

In [164]:
grouped[['Rank', 'Points']].agg([np.sum, np.mean, np.std])

Rank                     Points                        
        sum      mean       std    sum        mean         std
Team                                                          
Devils    5  2.500000  0.707107   1536  768.000000  134.350288
Giant     4  4.000000       NaN    812  812.000000         NaN
Kings     5  1.666667  1.154701   2285  761.666667   24.006943
Riders    7  1.750000  0.500000   3281  820.250000  101.068871
Royals    5  2.500000  2.121320   1525  762.500000   58.689863

In [165]:
grouped['Points'].mean()

Team
Devils    768.000000
Giant     812.000000
Kings     761.666667
Riders    820.250000
Royals    762.500000
Name: Points, dtype: float64

In [166]:
df.groupby('Team')['Points'].mean()

Team
Devils    768.000000
Giant     812.000000
Kings     761.666667
Riders    820.250000
Royals    762.500000
Name: Points, dtype: float64

In [167]:
phone = pd.read_csv('./phone_data.csv')
phone.head()

index            date  duration  item    month   network network_type
0      0  15/10/14 06:58    34.429  data  2014-11      data         data
1      1  15/10/14 06:58    13.000  call  2014-11  Vodafone       mobile
2      2  15/10/14 14:46    23.000  call  2014-11    Meteor       mobile
3      3  15/10/14 14:48     4.000  call  2014-11     Tesco       mobile
4      4  15/10/14 17:27     4.000  call  2014-11     Tesco       mobile

In [168]:
phone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   index         830 non-null    int64  
 1   date          830 non-null    object 
 2   duration      830 non-null    float64
 3   item          830 non-null    object 
 4   month         830 non-null    object 
 5   network       830 non-null    object 
 6   network_type  830 non-null    object 
dtypes: float64(1), int64(1), object(5)
memory usage: 29.2+ KB


In [170]:
phone['date'][0][-5:-3]

'06'

In [172]:
phone['time'] = phone['date'].apply(lambda x: x[-5:-3])

In [173]:
phone.head()

index            date  duration  item    month   network network_type time
0      0  15/10/14 06:58    34.429  data  2014-11      data         data   06
1      1  15/10/14 06:58    13.000  call  2014-11  Vodafone       mobile   06
2      2  15/10/14 14:46    23.000  call  2014-11    Meteor       mobile   14
3      3  15/10/14 14:48     4.000  call  2014-11     Tesco       mobile   14
4      4  15/10/14 17:27     4.000  call  2014-11     Tesco       mobile   17

In [174]:
phone.groupby('time')['duration'].mean()

time
00     23.600000
01      1.285714
02     56.600000
06     34.287086
07      3.285714
08    109.555556
09     95.947368
10     75.459459
11    102.953488
12    262.224490
13    151.480769
14     96.071429
15    224.513514
16    221.177778
17    135.350877
18    159.737705
19    196.042553
20    161.147059
21     52.800000
22      2.444444
23     54.947368
Name: duration, dtype: float64

In [176]:
phone[phone['item']=='call'].groupby('month')['duration'].mean()

month
2014-11    238.757009
2014-12    171.658228
2015-01    193.977273
2015-02    215.164179
2015-03    462.276596
Name: duration, dtype: float64

In [177]:
phone.groupby('item')['month'].value_counts()

item  month  
call  2014-11    107
      2015-01     88
      2014-12     79
      2015-02     67
      2015-03     47
data  2015-01     31
      2015-02     31
      2014-12     30
      2014-11     29
      2015-03     29
sms   2014-11     94
      2015-01     86
      2014-12     48
      2015-02     39
      2015-03     25
Name: month, dtype: int64

In [181]:
phone[['item', 'month']].count()

item     830
month    830
dtype: int64

In [189]:
phone.groupby(['item', 'month'])['date'].count()

item  month  
call  2014-11    107
      2014-12     79
      2015-01     88
      2015-02     67
      2015-03     47
data  2014-11     29
      2014-12     30
      2015-01     31
      2015-02     31
      2015-03     29
sms   2014-11     94
      2014-12     48
      2015-01     86
      2015-02     39
      2015-03     25
Name: date, dtype: int64

In [190]:
phone.groupby(['item', 'month'])['date'].count().unstack()

month  2014-11  2014-12  2015-01  2015-02  2015-03
item                                              
call       107       79       88       67       47
data        29       30       31       31       29
sms         94       48       86       39       25

In [191]:
grouped = phone.groupby('month')
grouped.get_group('2015-02')

index            date  duration  item    month   network network_type  \
577    577  13/01/15 06:58    34.429  data  2015-02      data         data   
586    586  14/01/15 06:58    34.429  data  2015-02      data         data   
594    594  15/01/15 06:58    34.429  data  2015-02      data         data   
595    595  15/01/15 10:36    28.000  call  2015-02     Three       mobile   
596    596  15/01/15 12:23     1.000   sms  2015-02   special      special   
..     ...             ...       ...   ...      ...       ...          ...   
724    724  10/02/15 00:24     1.000   sms  2015-02  Vodafone       mobile   
725    725  10/02/15 06:58    34.429  data  2015-02      data         data   
726    726  10/02/15 21:40     1.000   sms  2015-02  Vodafone       mobile   
727    727  11/02/15 06:58    34.429  data  2015-02      data         data   
728    728  12/02/15 06:58    34.429  data  2015-02      data         data   

    time  
577   06  
586   06  
594   06  
595   10  
596   12  
..   ...  
724   00  
725   06  
726   21  
727   06  
728   06  

[137 rows x 8 columns]

In [192]:
grouped.agg(sum)

index   duration
month                     
2014-11   26337  26639.441
2014-12   48362  14641.870
2015-01  100259  18223.299
2015-02   90398  15522.299
2015-03   78679  22750.441

In [194]:
grouped.agg({'duration':sum})

duration
month             
2014-11  26639.441
2014-12  14641.870
2015-01  18223.299
2015-02  15522.299
2015-03  22750.441

In [196]:
grouped.agg({'duration':sum, 'network_type':'count', 'date':'first'})

duration  network_type            date
month                                           
2014-11  26639.441           230  15/10/14 06:58
2014-12  14641.870           157  13/11/14 06:58
2015-01  18223.299           205  13/12/14 06:58
2015-02  15522.299           137  13/01/15 06:58
2015-03  22750.441           101  12/02/15 20:15

In [198]:
grouped = phone.groupby(['month', 'item'])
grouped.agg({'duration':sum, 'network_type':'count', 'date':'first'})

duration  network_type            date
month   item                                         
2014-11 call  25547.000           107  15/10/14 06:58
        data    998.441            29  15/10/14 06:58
        sms      94.000            94  16/10/14 22:18
2014-12 call  13561.000            79  14/11/14 17:24
        data   1032.870            30  13/11/14 06:58
        sms      48.000            48  14/11/14 17:28
2015-01 call  17070.000            88  15/12/14 20:03
        data   1067.299            31  13/12/14 06:58
        sms      86.000            86  15/12/14 19:56
2015-02 call  14416.000            67  15/01/15 10:36
        data   1067.299            31  13/01/15 06:58
        sms      39.000            39  15/01/15 12:23
2015-03 call  21727.000            47  12/02/15 20:15
        data    998.441            29  13/02/15 06:58
        sms      25.000            25  19/02/15 18:46

In [199]:
grouped.agg({'duration':[min, max, sum], 'network_type':'count', 'date':[min,'first','unique']})

duration                       network_type            date  \
                  min        max        sum        count             min   
month   item                                                               
2014-11 call    1.000   1940.000  25547.000          107  01/11/14 15:13   
        data   34.429     34.429    998.441           29  01/11/14 06:58   
        sms     1.000      1.000     94.000           94  03/11/14 08:40   
2014-12 call    2.000   2120.000  13561.000           79  02/12/14 11:40   
        data   34.429     34.429   1032.870           30  01/12/14 06:58   
        sms     1.000      1.000     48.000           48  01/12/14 12:51   
2015-01 call    2.000   1859.000  17070.000           88  02/01/15 11:27   
        data   34.429     34.429   1067.299           31  01/01/15 06:58   
        sms     1.000      1.000     86.000           86  02/01/15 23:26   
2015-02 call    1.000   1863.000  14416.000           67  01/02/15 13:33   
        data   34.429     34.429   1067.299           31  01/02/15 06:58   
        sms     1.000      1.000     39.000           39  02/02/15 17:35   
2015-03 call    2.000  10528.000  21727.000           47  01/03/15 12:19   
        data   34.429     34.429    998.441           29  01/03/15 06:58   
        sms     1.000      1.000     25.000           25  02/03/15 09:19   

                              \
                       first   
month   item                   
2014-11 call  15/10/14 06:58   
        data  15/10/14 06:58   
        sms   16/10/14 22:18   
2014-12 call  14/11/14 17:24   
        data  13/11/14 06:58   
        sms   14/11/14 17:28   
2015-01 call  15/12/14 20:03   
        data  13/12/14 06:58   
        sms   15/12/14 19:56   
2015-02 call  15/01/15 10:36   
        data  13/01/15 06:58   
        sms   15/01/15 12:23   
2015-03 call  12/02/15 20:15   
        data  13/02/15 06:58   
        sms   19/02/15 18:46   

                                                                 
                                                         unique  
month   item                                                     
2014-11 call  [15/10/14 06:58, 15/10/14 14:46, 15/10/14 14:4...  
        data  [15/10/14 06:58, 16/10/14 06:58, 17/10/14 06:5...  
        sms   [16/10/14 22:18, 16/10/14 22:21, 17/10/14 10:5...  
2014-12 call  [14/11/14 17:24, 16/11/14 14:05, 19/11/14 14:0...  
        data  [13/11/14 06:58, 14/11/14 06:58, 15/11/14 06:5...  
        sms   [14/11/14 17:28, 18/11/14 08:22, 18/11/14 08:2...  
2015-01 call  [15/12/14 20:03, 17/12/14 18:08, 18/12/14 12:3...  
        data  [13/12/14 06:58, 14/12/14 06:58, 15/12/14 06:5...  
        sms   [15/12/14 19:56, 15/12/14 19:58, 15/12/14 20:1...  
2015-02 call  [15/01/15 10:36, 15/01/15 17:22, 16/01/15 09:4...  
        data  [13/01/15 06:58, 14/01/15 06:58, 15/01/15 06:5...  
        sms   [15/01/15 12:23, 16/01/15 18:07, 19/01/15 12:4...  
2015-03 call  [12/02/15 20:15, 12/02/15 20:51, 13/02/15 10:5...  
        data  [13/02/15 06:58, 14/02/15 06:58, 15/02/15 06:5...  
        sms   [19/02/15 18:46, 19/02/15 22:00, 24/02/15 13:3...

In [200]:
raw_data = {
    'subject_id': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'],
    'test_score': [51,15,15,61,16,16,14,15,1,61,16]
}
df_a = pd.DataFrame(raw_data)
df_a

subject_id  test_score
0           1          51
1           2          15
2           3          15
3           4          61
4           5          16
5           6          16
6           7          14
7           8          15
8           9           1
9          10          61
10         11          16

In [201]:
raw_data = {
    'subject_id': ['4','5','6','12','13'],
    'first_name': ['Billy', 'Brain', 'Bran', 'Bryce', 'Betty'],
    'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']
}

df_b = pd.DataFrame(raw_data)
df_b

subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brain     Black
2          6       Bran   Balwner
3         12      Bryce     Brice
4         13      Betty    Btisan

In [202]:
pd.merge(df_a, df_b, on='subject_id', how='inner')

subject_id  test_score first_name last_name
0          4          61      Billy    Bonder
1          5          16      Brain     Black
2          6          16       Bran   Balwner

In [203]:
pd.merge(df_a, df_b, on='subject_id', how='left')

subject_id  test_score first_name last_name
0           1          51        NaN       NaN
1           2          15        NaN       NaN
2           3          15        NaN       NaN
3           4          61      Billy    Bonder
4           5          16      Brain     Black
5           6          16       Bran   Balwner
6           7          14        NaN       NaN
7           8          15        NaN       NaN
8           9           1        NaN       NaN
9          10          61        NaN       NaN
10         11          16        NaN       NaN

In [204]:
pd.merge(df_a, df_b, on='subject_id', how='right')

subject_id  test_score first_name last_name
0          4        61.0      Billy    Bonder
1          5        16.0      Brain     Black
2          6        16.0       Bran   Balwner
3         12         NaN      Bryce     Brice
4         13         NaN      Betty    Btisan

In [205]:
pd.merge(df_a, df_b, on='subject_id', how='outer')

subject_id  test_score first_name last_name
0           1        51.0        NaN       NaN
1           2        15.0        NaN       NaN
2           3        15.0        NaN       NaN
3           4        61.0      Billy    Bonder
4           5        16.0      Brain     Black
5           6        16.0       Bran   Balwner
6           7        14.0        NaN       NaN
7           8        15.0        NaN       NaN
8           9         1.0        NaN       NaN
9          10        61.0        NaN       NaN
10         11        16.0        NaN       NaN
11         12         NaN      Bryce     Brice
12         13         NaN      Betty    Btisan

In [206]:
pd.concat([df_a, df_b])

subject_id  test_score first_name last_name
0           1        51.0        NaN       NaN
1           2        15.0        NaN       NaN
2           3        15.0        NaN       NaN
3           4        61.0        NaN       NaN
4           5        16.0        NaN       NaN
5           6        16.0        NaN       NaN
6           7        14.0        NaN       NaN
7           8        15.0        NaN       NaN
8           9         1.0        NaN       NaN
9          10        61.0        NaN       NaN
10         11        16.0        NaN       NaN
0           4         NaN      Billy    Bonder
1           5         NaN      Brain     Black
2           6         NaN       Bran   Balwner
3          12         NaN      Bryce     Brice
4          13         NaN      Betty    Btisan

In [207]:
pd.concat([df_a, df_b], axis=1)

subject_id  test_score subject_id first_name last_name
0           1          51          4      Billy    Bonder
1           2          15          5      Brain     Black
2           3          15          6       Bran   Balwner
3           4          61         12      Bryce     Brice
4           5          16         13      Betty    Btisan
5           6          16        NaN        NaN       NaN
6           7          14        NaN        NaN       NaN
7           8          15        NaN        NaN       NaN
8           9           1        NaN        NaN       NaN
9          10          61        NaN        NaN       NaN
10         11          16        NaN        NaN       NaN

In [208]:
df = pd.read_csv('./phone_data.csv', index_col=0)
df.head()

date  duration  item    month   network network_type
index                                                                
0      15/10/14 06:58    34.429  data  2014-11      data         data
1      15/10/14 06:58    13.000  call  2014-11  Vodafone       mobile
2      15/10/14 14:46    23.000  call  2014-11    Meteor       mobile
3      15/10/14 14:48     4.000  call  2014-11     Tesco       mobile
4      15/10/14 17:27     4.000  call  2014-11     Tesco       mobile

In [209]:
df.pivot_table(['duration'],
              index = df.month,
              columns = df.item,
              aggfunc = 'count')

duration         
item        call data sms
month                    
2014-11      107   29  94
2014-12       79   30  48
2015-01       88   31  86
2015-02       67   31  39
2015-03       47   29  25

In [211]:
pd.crosstab(index = df.month,
           columns = df.network,
           values = df.duration,
           aggfunc = 'sum')

network  Meteor   Tesco    Three  Vodafone      data  landline  special  \
month                                                                     
2014-11  1531.0  4048.0  12483.0    4371.0   998.441    2906.0      1.0   
2014-12  2022.0  1820.0   6329.0    1320.0  1032.870    1424.0      NaN   
2015-01  2217.0  2907.0   6478.0    3666.0  1067.299    1603.0      NaN   
2015-02  1189.0  4089.0   6290.0    1887.0  1067.299     730.0      2.0   
2015-03   274.0   977.0   4971.0    3526.0   998.441   11770.0      NaN   

network  voicemail  world  
month                      
2014-11      301.0    NaN  
2014-12      690.0    4.0  
2015-01      285.0    NaN  
2015-02      268.0    NaN  
2015-03      231.0    3.0